apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "penpot.fullname" . }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
data:
  PENPOT_PUBLIC_URI: "{{ .Values.config.publicURI }}"
  PENPOT_FLAGS: "$PENPOT_FLAGS {{ .Values.config.flags }}"
  PENPOT_DATABASE_URI: "postgresql://{{ .Values.config.postgresql.host }}:{{ .Values.config.postgresql.port }}/{{ .Values.config.postgresql.database }}"
  PENPOT_REDIS_URI: "redis://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}/{{ .Values.config.redis.database }}"
  PENPOT_ASSETS_STORAGE_BACKEND: "{{ .Values.config.assets.storageBackend }}"
  PENPOT_STORAGE_ASSETS_FS_DIRECTORY: "{{ .Values.config.assets.filesystem.directory }}"
  PENPOT_STORAGE_ASSETS_S3_REGION: "{{ .Values.config.assets.s3.region }}"
  PENPOT_STORAGE_ASSETS_S3_BUCKET: "{{ .Values.config.assets.s3.bucket }}"
  PENPOT_TELEMETRY_ENABLED: {{ .Values.config.telemetryEnabled }}
  PENPOT_SMTP_DEFAULT_FROM: "{{ .Values.config.smtp.defaultFrom }}"
  PENPOT_SMTP_DEFAULT_REPLY_TO: "{{ .Values.config.smtp.defaultReplyTo }}"
  PENPOT_SMTP_HOST: "{{ .Values.config.smtp.host }}"
  PENPOT_SMTP_PORT: {{ .Values.config.smtp.port }}
  PENPOT_SMTP_TLS: {{ .Values.config.smtp.tls }}
  PENPOT_SMTP_SSL: {{ .Values.config.smtp.ssl }}
  PENPOT_REGISTRATION_DOMAIN_WHITELIST: "{{ .Values.config.registrationDomainWhitelist }}"
  PENPOT_GITLAB_BASE_URI: "{{ .Values.config.providers.gitlab.baseURI }}"
  PENPOT_OIDC_BASE_URI: "{{ .Values.config.providers.oidc.baseURI }}"
  PENPOT_OIDC_AUTH_URI: "{{ .Values.config.providers.oidc.authURI }}"
  PENPOT_OIDC_TOKEN_URI: "{{ .Values.config.providers.oidc.tokenURI }}"
  PENPOT_OIDC_USER_URI: "{{ .Values.config.providers.oidc.userURI }}"
  PENPOT_OIDC_ROLES: "{{ .Values.config.providers.oidc.roles }}"
  PENPOT_OIDC_ROLES_ATTR: "{{ .Values.config.providers.oidc.rolesAttribute }}"
  PENPOT_OIDC_SCOPES: "{{ .Values.config.providers.oidc.scopes }}"
  PENPOT_OIDC_NAME_ATTR: "{{ .Values.config.providers.oidc.nameAttribute }}"
  PENPOT_OIDC_EMAIL_ATTR: "{{ .Values.config.providers.oidc.emailAttribute }}"
  PENPOT_LDAP_HOST: "{{ .Values.config.providers.ldap.host }}"
  PENPOT_LDAP_PORT: {{ .Values.config.providers.ldap.port }}
  PENPOT_LDAP_SSL: {{ .Values.config.providers.ldap.ssl }}
  PENPOT_LDAP_STARTTLS: {{ .Values.config.providers.ldap.startTLS }}
  PENPOT_LDAP_BASE_DN: "{{ .Values.config.providers.ldap.baseDN }}"
  PENPOT_LDAP_BIND_DN: "{{ .Values.config.providers.ldap.bindDN }}"
  PENPOT_LDAP_BIND_PASSWORD: "{{ .Values.config.providers.ldap.bindPassword }}"
  PENPOT_LDAP_ATTRS_USERNAME: "{{ .Values.config.providers.ldap.attributesUsername }}"
  PENPOT_LDAP_ATTRS_EMAIL: "{{ .Values.config.providers.ldap.attributesEmail }}"
  PENPOT_LDAP_ATTRS_FULLNAME: "{{ .Values.config.providers.ldap.attributesFullname }}"
  PENPOT_LDAP_ATTRS_PHOTO: "{{ .Values.config.providers.ldap.attributesPhoto }}"
