apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
