{{- if .Values.sidekiq.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mastodon.fullname" . }}-sidekiq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mastodon.fullname" . }}-sidekiq
  minReplicas: {{ .Values.sidekiq.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sidekiq.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.sidekiq.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sidekiq.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sidekiq.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sidekiq.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
