{{- if and .Values.persistence.system.enabled (not .Values.persistence.system.existingClaim) (eq .Values.config.storage.type "fs") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mastodon.fullname" . }}-system
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
{{- if .Values.persistence.system.annotations }}
  annotations:
{{ toYaml .Values.persistence.system.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.system.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.system.size | quote }}
{{- if .Values.persistence.system.storageClass }}
  storageClassName: "{{ .Values.persistence.system.storageClass }}"
{{- end }}
{{- end }}
